<?php
function tax_tree_taxonomy_tree($vocabulary_name, $type = 0) {
    $vid = taxonomy_vocabulary_machine_name_load($vocabulary_name)->vid;
    $terms = taxonomy_get_tree($vid);
    $items =_tax_tree_taxonomy_tree($terms, 0 , $vocabulary_name);

    $tag_good  = false;
    $tag_company = false;
    switch ($vocabulary_name){
           case 'company_tags' : $term = true; $tag_company = true; break;
           case 'goods_tags' : $tag_good = true; break;
    }
   if ($tag_company ){
       $node = node_load(258);
       $file = file_create_url($node->field_image['und'][0]['uri']);
       $items[] = array(
           'data' => '<div class="list-tree-element"><img src="'.$file.'" alt=""></div>',
           'children' => array()
       );
   }
   if ($tag_good){
       $node = node_load(261);
       $file = file_create_url($node->field_image['und'][0]['uri']);
       $items[] = array(
           'data' => '<div class="list-tree-element"><img src="'.$file.'" alt=""></div>',
           'children' => array()
       );
   }


    return theme('item_list', array('items' =>  $items ));
}

/**
 * Helper for mymodule_taxonomy_tree()
 */
function _tax_tree_taxonomy_tree($terms, $parent = 0, $type = 0) {
    $items = array();
    switch ($type){
        case 'company_category' : $term = true;break;
        case 'company_tags' : $term = true; $tag = true; break;
    }
    foreach ($terms as $key => $term) {
        if (in_array($parent, $term->parents)) {

            if ($term ){
                $path = str_replace(' ', '-',transliteration_get($term->name));
                $path = "/category/company/".strtolower($path);
            }
            else{
                $path = "#";
            }
            $items[] = array(
                'data' => '<span >+</span><div class="list-tree-element"><a href="'.$path.'" id=' .$term->tid.' >'.$term->name.'</a></div>',
                'children' => _tax_tree_taxonomy_tree($terms, $term->tid),
            );
        }
    }

    return $items;
}

?>