<?php
function tax_tree_taxonomy_tree($vocabulary_name) {
    $vid = taxonomy_vocabulary_machine_name_load($vocabulary_name)->vid;
    $terms = taxonomy_get_tree($vid);
    dpm( _tax_tree_taxonomy_tree($terms));
    return theme('item_list', array('items' => _tax_tree_taxonomy_tree($terms)));
}

/**
 * Helper for mymodule_taxonomy_tree()
 */
function _tax_tree_taxonomy_tree($terms, $parent = 0) {
    $items = array();

    foreach ($terms as $term) {
        if (in_array($parent, $term->parents)) {
            $items[] = array(
                'data' => '<span >+</span><div class="list-tree-element"><a href="#" id=' .$term->tid.' >'.$term->name.'</a></div>',
                'children' => _tax_tree_taxonomy_tree($terms, $term->tid),
            );
        }
    }
    return $items;
}

?>