<?php


function company_admin_menu()
{

    $items['company/%'] = array(
        'title' => 'My gallery',
        'page callback' => 'company_page',
        'page arguments' => array(1, 'main-page'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'company-menu',
    );

    $items['company/%/products'] = array(
        'title' => 'My gallery',
        'page callback' => 'company_page',
        'page arguments' => array(1,'products-page'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'company-menu',
    );
    $items['company/%/news'] = array(
        'title' => 'My gallery',
        'page callback' => 'company_page',
        'page arguments' => array(1 , 'news-page'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'company-menu',
    );
    $items['company/%/gallery'] = array(
        'title' => 'My gallery',
        'page callback' => 'company_page',
        'page arguments' => array(1 , 'gallery-page'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'company-menu',
    );

    $items['company/%/reviews'] = array(
        'title' => 'My gallery',
        'page callback' => 'company_page',
        'page arguments' => array(1 , 'review-page'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
        'menu_name' => 'company-menu',
    );


    $items['example/%'] = array(
        'title' => 'My Page',
        'page callback' => 'show_link',
        'access callback' => 'example_user_has_role',
        'access arguments' => array(1, array('company_admin')), // arg 1 loads the user, arg 2 is the role name
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function show_link()
{
    $company = company_admin_get_company();
    return '<a href="/node/' . $company->nid . '/edit" > Редактировать компанию </a>';
}

function example_user_has_role($user, $roles = array())
{
    $current_user = user_load_by_name($user);
    if (  $current_user && $roles) {
        foreach ($roles as $role) {
                 if (in_array($role, $current_user->roles)) {
                return TRUE;
            }
        }
    }
    return false;
}
function company_page($node_title, $type){
    $node = get_node_by_alias($node_title);
    $template_name ="";
    switch ($type){
        case 'main-page': $template_name ="main"; break;
        case 'products-page': $template_name ="news"; break;
        case 'news-page': $template_name ="products"; break;
        case 'gallery-page': $template_name ="gallery"; break;
        case 'review-page': $template_name ="review"; break;
    }


    return theme($template_name.'_template', array('node' => $node)); // call a theme or you have no pass any argument in theme to change a 'nodes'=> NULL or 'pager'=>NULL
}


function company_admin_theme()
{
    return array(
        'main_template' => array(
            'template' => 'main-page',//this is file name of template file
            'variables' => array('nodes' => NULL, 'pager' => NULL), //this is pass avarible of templates file
            'path' => drupal_get_path('module', 'company_admin') . '/template' // set a path of file
        ),
        'products_template' => array(
            'template' => 'products-page',//this is file name of template file
            'variables' => array('nodes' => NULL, 'pager' => NULL), //this is pass avarible of templates file
            'path' => drupal_get_path('module', 'company_admin') . '/template' // set a path of file
        ),
        'news_template' => array(
            'template' => 'news-page',//this is file name of template file
            'variables' => array('nodes' => NULL, 'pager' => NULL), //this is pass avarible of templates file
            'path' => drupal_get_path('module', 'company_admin') . '/template' // set a path of file
        ),
        'gallery_template' => array(
            'template' => 'gallery-page',//this is file name of template file
            'variables' => array('nodes' => NULL, 'pager' => NULL), //this is pass avarible of templates file
            'path' => drupal_get_path('module', 'company_admin') . '/template' // set a path of file
        ),
        'review_template' => array(
            'template' => 'review-page',//this is file name of template file
            'variables' => array('nodes' => NULL, 'pager' => NULL), //this is pass avarible of templates file
            'path' => drupal_get_path('module', 'company_admin') . '/template' // set a path of file
        ),
    );
}

function company_admin_permission()         /// set new role for module permision
{
    return array(
        'access company module' => array(
            'title' => t('Access my test module'),
            'description' => t('Доступ к первой кастомной странице моего модуля')
        ));
}


function company_admin_node_validate($node, $form, &$form_state)
{

    global $user;
    $count = db_select('node', 'n')
        ->condition('n.uid', $user->uid)
        ->countQuery()
        ->execute()
        ->fetchField();

    if ($count > 0 &&  !$node->nid && $user->uid != 1 && $node->type=="company" ) {
        form_set_error('time', t('Вы не можете создать более, чем 1 компанию'));
    }
}

function company_admin_get_company()
{
    global $user;
    $nodes = db_select('node', 'n')
        ->fields('n')
        ->condition('n.type', 'company')
        ->condition('n.uid', $user->uid)
        ->execute()
        ->fetchAll();

    return $nodes[0];
}
function company_admin_node_presave($node){
    if ($node->type == 'goods' ){
        $company = company_admin_get_company();
        $node->field_company['und'][0]['target_id'] = $company->nid;
        $alias = explode('/',drupal_get_path_alias('node/'.$company->nid));

        $node->field_alias['und'][0]['value'] = $alias[1];
    }

    if ($node->type == 'company_news' ){
        $company = company_admin_get_company();
        $node->field_company['und'][0]['target_id'] = $company->nid;
    }
    if ($node->type == 'photogallery' ){
        $company = company_admin_get_company();
        $node->field_company['und'][0]['target_id'] = $company->nid;


    }



}

function get_node_by_alias($node_title) {
    $alias = "company/" . $node_title.'/about';
    $path = drupal_lookup_path("source", $alias);
    $node = menu_get_object("node", 1, $path);
    return $node;

}





